### ISSUE TITLE
History of operations

### ISSUE THREAD

**Issue by ivkalgin** [ExecutionLLC/ethereum_stock#1]
Добавить историю посл. 5 операций (покупка/продажа токенов) в блок под строку баланса пользователя. 

Пример:
date_time/operation_type/number_of_tokens/token_price(ETH)
16.06.2017 16:00    Purchased    3   1
20.06.2017 12:22    Purchased    1   2
20.06.2017 23:30    Sold              2   4

**Comment by ZzDmitry** [comment]
Поправка: колонка с ценой токена не нужна.
