### ISSUE TITLE
Операции с кошельком пользователя

### ISSUE THREAD

**Issue by ivkalgin** [ExecutionLLC/ethereum_stock#2]
Требуется добавить функционал работы с кошельком пользователя. Цель:
1. Предоставить возможность завести новый кошелек для покупок
2. Предоставить возможность проведения транзакций через существующий кошелёк (подтверждение либо по private key, либо по json_utс файлу)
3. Добавить на страницу отдельный блок для проведения операций требующих перевода криптовалюты (покупка токенов/продажа токенов)

Пример:
https://medium.com/@BitHope.org/how-to-send-ether-to-%C3%A6ternitys-contribution-campaign-wallet-e11ef89b847e

**Comment by ivkalgin** [comment]
Начать можно вот с этого:
https://github.com/SilentCicero/ethers-wallet
https://github.com/ethers-io/ethers.js/tree/master <-- предпочтительней

**Comment by ZzDmitry** [comment]
Базовый функционал есть в ff4b692bb0b68ed71084163372c36c969436bc0f
