### ISSUE TITLE
Дизайн веб странички 

### ISSUE THREAD

**Issue by AlexandrKirienko** [ExecutionLLC/ethereum_stock#3]
Прототип дизайна для разработки страницы. 
http://ta2zmm.axshare.com/#g=1&p=home&c=1

**Comment by ZzDmitry** [comment]
Оказалось, что с этой вёрсткой крайне сложно иметь дело. Азуровких тонкостей не знаю, потому взял всю страницу, что есть, вместо со скриптами и стилями. Всё элементы спозиционированы абсолютно, то есть стоят на строго определённых координатах. То есть добавить элементы, особенно если они динамические (например история последних операций), очень сложно - нужно подгонять под координаты. Скрипты чувствительны к вёрстке, то есть просто даже добавить элемент и не получить ошибку где-то в азуровских скриптах - нужно постараться.
Возможно, из прототипа как-то предполагается получать вёрстку в нормальном виде, но я сходу этого не нашёл.

**Comment by ZzDmitry** [comment]
Снаружи можно на страничку зайти на мой комп:
http://37.195.64.171:2080/public/index.html
По дизайну, конечно, ещё работать, но функционал есть.

**Comment by ZzDmitry** [comment]
Текущая версия http://37.195.64.171:2080/eth/public/index.html
Задачу закрываю, дизайн устоялся, далее работаем в его улучшении.
